import { Inter } from 'next/font/google'
import './globals.scss'
import Menu from '@/components/Menu'
import Rodape from '@/components/Rodape'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Porto Seguro',
  description: 'Generated by FIAP',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu />
        {children}
        <Rodape />
      </body>
    </html>
  )
}
